steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build','-t', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2', . ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'app-angular-gcp-ui'
  - '--image'
  - 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2'
  - '--region'
  - 'us-central1-c'
         
images:
- gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2
