steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build','-t', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v5', . ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v5']
- id: 'deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  env:
   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-demo'
   - 'KUBECONFIG=/kube/config'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
       
        gcloud container clusters get-credentials demo-cluster  \
            --project elevated-server-275615 \
            --zone us-central1-c     
        		
        sed -i 's|gcr.io/elevated-server-275615/app-angular-gcp-ui:.*|gcr.io/"${PROJECT_ID}"/app-angular-gcp-ui:v5|' ./manifest.yaml
        
        
        kubectl get ns default || kubectl create ns default
        kubectl apply --namespace default --recursive -f manifest.yaml
images:
- gcr.io/$PROJECT_ID/app-angular-gcp-ui:v5
