steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build','-t', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui', . ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui']
- id: 'deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  env:
   - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
   - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
   - 'KUBECONFIG=/kube/config'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone) 
        
        gcloud container clusters get-credentials sandbox-gke  \
            --project elevated-server-275615 \
            --zone us-central1     
                
        
        sed -i 's|gcr.io/"$${PROJECT}"/app-angular-gcp-ui:.*|gcr.io/"$${PROJECT}"/app-angular-gcp-ui|' ./manifest.yaml
        
        
        kubectl apply -f manifest.yaml --record
