steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build','-t', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui', . ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui']
- id: 'deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  env:
   - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'
   - 'KUBECONFIG=/kube/config'
  entrypoint: 'bash'
  args:
    - '-c'
    - | kubectl apply -f manifest.yaml --record
