steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build','-t', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2', . ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2']
- id: 'deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  env:
   - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'
   - 'KUBECONFIG=/kube/config'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone) 
        
        gcloud container clusters get-credentials demo-cluster  \
            --project elevated-server-275615 \
            --zone us-central1-c
        kubectl apply -f manifest.yaml --record
		kubectl set image deployment app-angular-gcp-ui app-angular-gcp-ui=app-angular-gcp-ui:v2       
images:
- gcr.io/$PROJECT_ID/app-angular-gcp-ui:v2
